// Generated by gencpp from file rplidar_ros/tilterRequest.msg
// DO NOT EDIT!


#ifndef RPLIDAR_ROS_MESSAGE_TILTERREQUEST_H
#define RPLIDAR_ROS_MESSAGE_TILTERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rplidar_ros
{
template <class ContainerAllocator>
struct tilterRequest_
{
  typedef tilterRequest_<ContainerAllocator> Type;

  tilterRequest_()
    : command()
    , argument(0.0)  {
    }
  tilterRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , argument(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;

   typedef float _argument_type;
  _argument_type argument;





  typedef boost::shared_ptr< ::rplidar_ros::tilterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rplidar_ros::tilterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct tilterRequest_

typedef ::rplidar_ros::tilterRequest_<std::allocator<void> > tilterRequest;

typedef boost::shared_ptr< ::rplidar_ros::tilterRequest > tilterRequestPtr;
typedef boost::shared_ptr< ::rplidar_ros::tilterRequest const> tilterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rplidar_ros::tilterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rplidar_ros::tilterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rplidar_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rplidar_ros::tilterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rplidar_ros::tilterRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rplidar_ros::tilterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rplidar_ros::tilterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rplidar_ros::tilterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rplidar_ros::tilterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rplidar_ros::tilterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "93e7c23e203f5f12cb2e86672a6415c3";
  }

  static const char* value(const ::rplidar_ros::tilterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x93e7c23e203f5f12ULL;
  static const uint64_t static_value2 = 0xcb2e86672a6415c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::rplidar_ros::tilterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rplidar_ros/tilterRequest";
  }

  static const char* value(const ::rplidar_ros::tilterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rplidar_ros::tilterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n"
"float32 argument\n"
;
  }

  static const char* value(const ::rplidar_ros::tilterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rplidar_ros::tilterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.argument);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tilterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rplidar_ros::tilterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rplidar_ros::tilterRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
    s << indent << "argument: ";
    Printer<float>::stream(s, indent + "  ", v.argument);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RPLIDAR_ROS_MESSAGE_TILTERREQUEST_H
